apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-helpdesk-ui
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-helpdesk-ui  
  template:
    metadata:
      labels:
        app: i27-helpdesk-ui
    spec:
      containers:
        - name: i27-helpdesk-ui
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          resource:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"